name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: |
          npm ci
          npm link
          npm link astro-themes
      - name: Check code
        run: npm run check:code
      - name: Check formatting
        run: npm run check:format
      - name: Check styles
        run: npm run check:styles
      - name: Check commit messages
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: |
          npm ci
          npm link
          npm link astro-themes
      - name: Install Playwright Browsers
        run: npm run test:install
      - name: Run Playwright tests
        run: npm test
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
